service: gadmin-service

package:
  exclude:
    - venv/**
    - __pycache__/**
    - node_modules/**

provider:
  name: aws
  runtime: python3.6
  region: ap-southeast-1
  timeout: 300
  apiKeys:
    - gadmin-api-key
  deploymentBucket:
    name: gadmin-lambda
  deploymentPrefix: gadmin
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: arn:aws:s3:::gadmin-lambda/*




functions:
  listAccountUsers:
    handler: gadmin.handleListAccountUsers
    events:
      - http:
          path: /users
          method: get
          private: true
          cors:
            origins:
              - '*'
  listViewUsers:
    handler: gadmin.handleListViewUsers
    events:
      - http:
          path: /users/{propertyId}/{viewId}
          method: get
          private: true
          cors:
            origins:
              - '*'
          request:
            parameters:
              paths:
                propertyId: true
                viewId: true
  listTags:
    handler: gadmin.handleListTags
    events:
      - http:
          path: /tags/{containerId}
          method: get
          private: true
          cors:
            origins:
              - '*'
          request:
            parameters:
              paths:
                containerId: true

plugins:
  - serverless-python-requirements
  - serverless-prune-plugin
custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
  prune:
    automatic: true
    number: 3
